name: Build and Commit Firmware to Files

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Set up arduino-cli
      run: |
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
        sudo mv bin/arduino-cli /usr/local/bin/
        arduino-cli config init

    - name: Install ESP32 Core
      run: |
        arduino-cli core update-index
        arduino-cli core install esp32:esp32

    - name: Install libraries
      run: arduino-cli lib install "ArduinoJson"

    - name: Compile sketch
      run: |
        arduino-cli compile --fqbn esp32:esp32:esp32 src --output-dir ./build

    - name: Rename output to firmware.bin
      run: mv ./build/src.ino.bin ./firmware.bin

    - name: Extract version and generate firmware.json
      run: |
        VERSION=$(grep 'const char\* current_version' src/*.ino | sed -E 's/.*"(.+)".*/\1/')
        echo "Version: $VERSION"
        rm -rf files
        mkdir -p files
        echo "{" > files/firmware.json
        echo "  \"version\": \"$VERSION\"," >> files/firmware.json
        echo "  \"url\": \"https://raw.githubusercontent.com/haider00727/ota-esp32/main/files/firmware.bin\"" >> files/firmware.json
        echo "}" >> files/firmware.json
        mv firmware.bin files/

    - name: Commit and push firmware files
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add -A files/
        git commit -m "Update firmware to version $VERSION - " || echo "No changes to commit"
        git push
