name: Build and Upload ESP32 Firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up arduino-cli
      run: |
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
        sudo mv bin/arduino-cli /usr/local/bin/
        arduino-cli config init

    - name: Install ESP32 Core
      run: |
        arduino-cli core update-index
        arduino-cli core install esp32:esp32
    - name: Install ArduinoJson library
      run: arduino-cli lib install "ArduinoJson"

    - name: Compile Sketch
      run: |
        arduino-cli compile --fqbn esp32:esp32:esp32 src --output-dir ./build

    - name: Upload firmware to OSS
      run: |
        curl -X PUT --upload-file "./build/src.ino.bin" \
          "http://devtestego.oss-me-central-1.aliyuncs.com/firmware.bin"

    - name: Extract version from code and generate firmware.json
      run: |
        VERSION=$(grep 'const char\* current_version' src/*.ino | sed -E 's/.*"(.+)".*/\1/')
        echo "Version found: $VERSION"

        cat <<EOF > firmware.json
{
  "version": "$VERSION",
  "url": "http://devtestego.oss-me-central-1.aliyuncs.com/firmware.bin"
}
EOF

    - name: Upload firmware.bin and firmware.json to OSS
      run: |
        curl -X PUT --upload-file "./build/src.ino.bin" \
          "http://devtestego.oss-me-central-1.aliyuncs.com/firmware.bin"

        curl -X PUT --upload-file "firmware.json" \
          "http://devtestego.oss-me-central-1.aliyuncs.com/firmware.json"
