name: Build and Upload Static Firmware Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up arduino-cli
      run: |
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
        sudo mv bin/arduino-cli /usr/local/bin/
        arduino-cli config init

    - name: Install ESP32 Core
      run: |
        arduino-cli core update-index
        arduino-cli core install esp32:esp32

    - name: Install libraries
      run: arduino-cli lib install "ArduinoJson"

    - name: Compile sketch
      run: |
        arduino-cli compile --fqbn esp32:esp32:esp32 src --output-dir ./build

    - name: Extract version and generate firmware.json
      run: |
        VERSION=$(grep 'const char\* current_version' src/*.ino | sed -E 's/.*"(.+)".*/\1/')
        echo "Version: $VERSION"

        echo "{" > firmware.json
        echo "  \"version\": \"$VERSION\"," >> firmware.json
        echo "  \"url\": \"https://github.com/haider00727/ota-esp32/releases/latest/download/firmware.bin\"" >> firmware.json
        echo "}" >> firmware.json

    - name: Upload firmware to 'latest' release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest
        name: Latest OTA Firmware
        files: |
          ./build/src.ino.bin
          firmware.json
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}  # <-- Use your personal access token here
