    - name: Install ESP32 Core
      run: |
        arduino-cli core update-index
        arduino-cli core install esp32:esp32

    - name: Install dependencies
      run: |
        arduino-cli lib install "ArduinoJson"

    - name: Compile Sketch
      run: |
        arduino-cli compile --fqbn esp32:esp32:esp32 src --output-dir ./build
