name: Build and Commit Firmware to Files

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Set up arduino-cli
      run: |
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
        sudo mv bin/arduino-cli /usr/local/bin/
        arduino-cli config init

    - name: Install ESP32 Core
      run: |
        arduino-cli core update-index
        arduino-cli core install esp32:esp32

    - name: Install libraries
      run: arduino-cli lib install "ArduinoJson"

    - name: Compile sketch
      run: |
        arduino-cli compile --fqbn esp32:esp32:esp32 src --output-dir ./build

    - name: Rename output to firmware.bin
      run: mv ./build/src.ino.bin ./firmware.bin

    - name: Extract version and generate firmware.json
      run: |
        VERSION=$(grep 'const char\* current_version' src/*.ino | sed -E 's/.*"(.+)".*/\1/')
        echo "Version: $VERSION"
        rm -rf files
        mkdir -p files
        echo "{" > files/firmware.json
        echo "  \"version\": \"$VERSION\"," >> files/firmware.json
        echo "  \"url\": \"http://raw.githubusercontent.com/haider00727/ota-esp32-files/main/firmware.bin\"" >> files/firmware.json
        echo "}" >> files/firmware.json

    - name: Move firmware files to 'files' directory
      run: |
        mv firmware.bin files/
        mv files/firmware.json files/

    - name: Commit and push firmware files
      run: |
        cd files
        git init
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git remote add origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/haider00727/ota-esp32-files.git
        git fetch origin || echo "Remote 'origin' not found, initializing"
        git checkout -b main || echo "Branch 'main' doesn't exist, creating it"
        git add firmware.bin firmware.json
        git commit -m "Update firmware to version $VERSION" || echo "No changes to commit"
        git push --set-upstream origin main || git push -u origin main
