name: Build and Upload Firmware to Alibaba OSS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up arduino-cli
      run: |
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
        sudo mv bin/arduino-cli /usr/local/bin/
        arduino-cli config init

    - name: Install ESP32 Core
      run: |
        arduino-cli core update-index
        arduino-cli core install esp32:esp32

    - name: Install libraries
      run: arduino-cli lib install "ArduinoJson"

    - name: Compile sketch
      run: |
        arduino-cli compile --fqbn esp32:esp32:esp32 src --output-dir ./build

    - name: Rename output to firmware.bin
      run: mv ./build/src.ino.bin ./firmware.bin

    - name: Extract version and generate firmware.json
      run: |
        VERSION=$(grep 'const char\* current_version' src/*.ino | sed -E 's/.*"(.+)".*/\1/')
        echo "Version: $VERSION"
        rm -rf files
        mkdir -p files
        echo "{" > files/firmware.json
        echo "  \"version\": \"$VERSION\"," >> files/firmware.json
        echo "  \"url\": \"https://devtestego.oss-me-central-1.aliyuncs.com/firmware.bin\"" >> files/firmware.json
        echo "}" >> files/firmware.json

    - name: Move firmware files to 'files' directory
      run: |
        mv firmware.bin files/  # Move firmware.bin to files folder
        # No need to move firmware.json since it's already in the correct folder
 
    - name: Check that firmware files exist
    run: |
        echo "Checking contents of files directory:"
        ls -la files/  # List the files in the 'files' directory
        cat files/firmware.json  # Display the contents of firmware.json

    - name: Upload firmware to OSS
    run: |
      # Upload firmware.bin to the OSS bucket
      curl -X PUT --upload-file "./firmware.bin" \
        "http://devtestego.oss-me-central-1.aliyuncs.com/firmware.bin"

      # Upload firmware.json to the OSS bucket
      curl -X PUT --upload-file "./firmware.json" \
        "http://devtestego.oss-me-central-1.aliyuncs.com/firmware.json"
